easy_admin:
    entities:
        Conference:
            class: App\Entity\Conference
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image', 'base_path': '/uploads/photos', label: 'Photo' }
                    - state
                    - { property: 'cratedAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['conference']