version: '3'
services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]
    redis:
        image: library/redis:5-alpine
        ports: [6379]
    rabbitmq:
        image: library/rabbitmq:3.7-management
        ports: [5672, 15672]